---
- name: Setup build environment
  ansible.builtin.import_tasks: dev.yml

- name: Install neovim
  ansible.builtin.import_tasks: neovim.yml

- name: Install opencode
  ansible.builtin.import_tasks: opencode.yml
