---
- name: "Install: opencode"
  ansible.builtin.shell: |
    curl -fsSL https://opencode.ai/install | bash
  args:
    creates: /home/vagrant/.opencode/bin/opencode

- name: Ensure the opencode config directory exists
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/opencode"
    state: directory
    mode: '0755' 

- name: Copy opencode.json 
  ansible.builtin.copy:
    src: opencode.json
    dest: "{{ home_dir }}/.config/opencode/opencode.json"
    mode: '0755'


